-- Add SR1, dogleg and cubic regularization (editorial scope TOPIC_SR1 / TOPIC_DOGLEG / TOPIC_CUBIC_REGULARIZATION).
-- SR1 is placed in MF_SMOOTH_LOCAL with BFGS/L-BFGS (a Hessian-approximation update); its trust-region pairing is kept in related_method_ids.
-- Dogleg is placed in MF_TRUST_REGION. Cubic regularization is placed in MF_SMOOTH_LOCAL: its globalization is a regularization
-- weight, not a trust radius, and it is the Newton method with a cubic term (see M_NEWTON).
-- No implementation rows: the existing SciPy implementation rows are per-solver and none covers dogleg, trust-exact or SR1.
PRAGMA foreign_keys = ON;

INSERT INTO sources (
  source_id, source_type, title, author_or_organization, publication_date,
  accessed_date, url, supported_claim, source_quality, notes, currentness_status
) VALUES
(
  'S124', 'original_paper',
  'Convergence of quasi-Newton matrices generated by the symmetric rank one update',
  'Andrew R. Conn; Nicholas I. M. Gould; Philippe L. Toint', '1991-03-01', '2026-10-10',
  'https://doi.org/10.1007/BF01594934',
  'SR1 matrices converge to the true Hessian under a uniform linear independence condition on the steps.',
  'primary', 'Mathematical Programming 50, 177-195 (1991), DOI 10.1007/BF01594934. Volume and pages confirmed on 2026-10-10 against the Springer record via search (some secondary sources cite volume 48, pp. 549-560, which is a citation error).',
  'historical_primary'
),
(
  'S125', 'original_paper',
  'A hybrid method for nonlinear equations',
  'M. J. D. Powell', '1970-01-01', '2026-10-10',
  'https://www.gnu.org/software/gsl/doc/html/multiroots.html',
  'Powell''s hybrid (dogleg) method for nonlinear equations: a step combining the Newton and steepest-descent directions within a step bound.',
  'primary', 'Chapter 6 in P. Rabinowitz (ed.), Numerical Methods for Nonlinear Algebraic Equations, Gordon and Breach, 1970, pp. 87-114. Pages confirmed on 2026-10-10 against the GNU Scientific Library documentation reference list (a publisher listing was not found; Wikipedia gives 87-144, which looks like a typo). The chapter has no stable online URL: the url field points to the GNU Scientific Library multiroots documentation, which lists this reference and describes the dogleg step (a documentation page, not the chapter itself). The textbook description is backed by Nocedal and Wright (S056).',
  'historical_primary'
),
(
  'S126', 'original_paper',
  'Cubic regularization of Newton method and its global performance',
  'Yurii Nesterov; B. T. Polyak', '2006-04-25', '2026-10-10',
  'https://doi.org/10.1007/s10107-006-0706-8',
  'Cubic regularization of Newton method: global worst-case complexity bounds for several problem classes including some nonconvex ones.',
  'primary', 'Mathematical Programming 108, 177-205 (2006), DOI 10.1007/s10107-006-0706-8. Confirmed on 2026-10-10 against the Springer record via search.',
  'historical_primary'
),
(
  'S127', 'original_paper',
  'Adaptive cubic regularisation methods for unconstrained optimization. Part I: motivation, convergence and numerical results',
  'Coralia Cartis; Nicholas I. M. Gould; Philippe L. Toint', '2011-04-01', '2026-10-10',
  'https://doi.org/10.1007/s10107-009-0286-5',
  'ARC: adaptive regularisation using cubics with adaptive estimation of the local Lipschitz constant and approximate model minimizers; compared with a basic trust-region implementation.',
  'primary', 'Mathematical Programming 127(2), 245-295 (2011), DOI 10.1007/s10107-009-0286-5. Confirmed on 2026-10-10 against the Springer record via search.',
  'historical_primary'
);

INSERT INTO methods (
  method_id, name_ja, name_en, aliases, method_family_id, method_level,
  summary, problem_classes, required_assumptions, derivative_information, variable_types, constraint_support,
  convex_fit, nonconvex_applicability, solution_scope, determinism, exactness, theoretical_guarantee,
  optimality_certificate, scalability, memory_tendency, per_iteration_cost, evaluation_pattern, parallelism,
  initialization_sensitivity, hyperparameter_sensitivity, scaling_sensitivity, noise_robustness, discontinuity_robustness, constraint_violation_handling,
  warm_start, online_use, strengths, weaknesses, typical_failures, avoid_conditions,
  first_choice_conditions, second_choice_conditions, switch_signals, beginner_level, tuning_difficulty, implementation_difficulty,
  explainability, stopping_criteria, diagnostic_metrics, related_method_ids, parent_method_id, child_method_ids,
  reference_source_ids, confidence, last_verified
) VALUES
(
  'M_SR1', 'SR1法', 'Symmetric rank-one (SR1) quasi-Newton update', 'SR1;symmetric rank-one;SR1 update', 'MF_SMOOTH_LOCAL', 'variant', 'gradient差から対称ランク1の補正でHessian近似を更新する準Newton法。更新後の近似が正定値とは限らず、不定な曲率も表現でき、trust regionと併用されることが多い。', '連続;滑らか;局所最適化', '目的が局所的に滑らか。gradientが信頼できる。更新のdenominatorが小さいときは更新を飛ばすなどの安全策が必要。', 'gradient', 'continuous', 'unconstrained', 'strong', 'yes_local_only', 'local', 'deterministic', 'local_numerical', 'step列が一様に線形独立などの仮定下で、SR1行列が真のHessianへ収束することが示されている(Conn, Gould, Toint 1991)。SR1単独での大域収束の保証はこの出典では示されていない。', 'first_order_residual;second_order_optional', 'low_to_medium', 'high_O(n2)_dense_approximation', '勾配とdenseな行列更新・線形代数。', '1回以上の目的・勾配評価。線探索・試行step棄却で追加評価。', 'limited_with_linear_algebra_parallelism', 'medium_nonconvex', 'medium', 'high', 'low', 'low', 'family_dependent', 'yes', 'conditional', '不定な曲率を近似できる;正定値性を強制するBFGSより真のHessianに近づく場合がある(出典の主張範囲);少ない評価回数', '更新のdenominatorが0に近いと破綻する;近似が不定のため線探索単独では使いにくく、trust regionなどの併用が前提になりやすい', 'denominator_breakdown;bad_gradient;ill_conditioning;indefinite_model_without_globalization', '不連続;評価ノイズが勾配を支配;離散変数', 'unknown', 'trust regionと併用でき、不定な曲率を準Newton近似で扱いたい滑らかな問題。', '勾配検査不一致;反復停滞;試行step棄却が続く;初期値で解が大きく変わる。', 'medium', 'medium', 'medium', 'high', 'gradient_norm;step_norm;objective_change;budget', 'gradient_norm;update_denominator;actual_predicted_ratio;function_evaluations', 'M_BFGS;M_LBFGS;M_TRUST_EXACT;M_TRUST_NCG', 'MF_SMOOTH_LOCAL', '', 'S124;S056;S002', 'medium', '2026-10-10'
),
(
  'M_DOGLEG', 'Dogleg法', 'Dogleg trust-region method', 'dogleg;Powell dogleg;Powell hybrid method', 'MF_TRUST_REGION', 'variant', 'Newtonステップと最急降下(Cauchy)方向のstepを折れ線(dogleg)でつなぎ、信頼領域境界との交点を試行stepにする。部分問題を閉形式で近似的に解く。', '連続;滑らか;局所最適化;非線形方程式', 'Hessian(または近似)が正定値であること。dense線形系を解けること。', 'gradient;hessian', 'continuous', 'unconstrained', 'strong', 'yes_local_only', 'local', 'deterministic', 'local_numerical', '試行stepがCauchy点以上の改善を保つ設計により、標準仮定下の信頼領域法の大域収束理論に載る(Nocedal and Wright)。Powell(1970)は非線形方程式向けのhybrid法として導入した。', 'first_order_residual;second_order_optional', 'low_to_medium', 'high_dense_hessian', 'モデル構築とdense線形solve(Newtonステップ)。信頼領域部分問題は折れ線上で安価に解く。', '1回以上の目的・勾配評価。線探索・試行step棄却で追加評価。', 'limited_with_linear_algebra_parallelism', 'medium_nonconvex', 'medium', 'high', 'low', 'low', 'family_dependent', 'yes', 'conditional', '部分問題が閉形式で安価;exact trust-regionより実装が単純', 'Hessian近似が正定値であることを前提とし、不定なHessianには対応しない;dense線形solveが必要', 'trust_radius_collapse;indefinite_hessian;bad_model;ill_conditioning', '不連続;強いノイズ;Hessianが不定または得られない;大規模問題', 'unknown', '正定値なdense Hessianが得られる中小規模問題で、厳密な部分問題解よりも安価な試行stepを使いたい場合。', '半径が縮小し続ける;モデル改善比が悪い;Hessianが不定。', 'medium', 'medium', 'medium', 'high', 'gradient_norm;trust_radius;model_reduction;budget', 'actual_predicted_ratio;trust_radius;rejected_steps;newton_step_norm', 'M_TRUST_EXACT;M_TRUST_NCG;M_NEWTON', 'MF_TRUST_REGION', '', 'S125;S056;S002', 'medium', '2026-10-10'
),
(
  'M_CUBIC_REGULARIZATION', '三次正則化法', 'Cubic regularization of Newton method (ARC)', 'cubic regularization;cubic regularisation;ARC;adaptive regularisation with cubics;Nesterov-Polyak', 'MF_SMOOTH_LOCAL', 'variant', '局所二次モデルに三次の正則化項を加えた部分問題を各反復で解くNewton型の方法。正則化の重みを適応的に調整するのがARC。', '連続;滑らか;局所最適化', '目的が二回微分可能でHessianが(局所的に)Lipschitz連続。Hessianまたはその近似が利用でき、三次正則化部分問題を(近似的に)解けること。', 'gradient;hessian_or_hvp', 'continuous', 'unconstrained', 'strong', 'yes_local_only', 'local', 'deterministic', 'local_numerical', 'Hessianのリプシッツ連続性の下で非凸問題を含む大域的な最悪ケース計算量境界が示されている(Nesterov and Polyak 2006)。ARCはLipschitz定数を適応的に推定し大域収束を示す(Cartis, Gould, Toint 2011)。', 'first_order_residual;second_order_optional', 'low_to_medium', 'medium_to_high', 'モデル構築と三次正則化部分問題(近似解法はKrylov等)。', '試行点ごとに目的評価。拒否時は正則化重みを増やし再評価。', 'limited_with_linear_algebra_parallelism', 'medium_nonconvex', 'medium', 'high', 'low', 'low', 'family_dependent', 'yes', 'conditional', '非凸問題でも大域的な計算量保証がある(出典の主張範囲);半径ではなく正則化重みで大域化する', '三次部分問題の解法とHessian品質に依存;実装が複雑;実用上の標準ソルバーは限られる', 'regularization_weight_blowup;bad_hessian;ill_conditioning;subproblem_inaccuracy', '不連続;評価ノイズが勾配を支配;離散変数', 'unknown', 'Hessian(または信頼できる近似)が得られ、非凸でも大域的な保証を重視する滑らかな問題。', '正則化重みが増え続ける;モデル改善比が悪い;部分問題が支配的。', 'low', 'medium', 'high', 'high', 'gradient_norm;step_norm;model_reduction;budget', 'gradient_norm;regularization_weight;actual_predicted_ratio;subproblem_iterations', 'M_NEWTON;M_TRUST_EXACT;M_LEVENBERG_MARQUARDT', 'MF_SMOOTH_LOCAL', '', 'S126;S127;S056', 'medium', '2026-10-10'
);

UPDATE methods
SET child_method_ids = 'M_GRADIENT_DESCENT;M_NLCG;M_NEWTON;M_NEWTON_CG;M_BFGS;M_LBFGS;M_LBFGSB;M_SR1;M_CUBIC_REGULARIZATION'
WHERE method_id = 'MF_SMOOTH_LOCAL';
UPDATE methods
SET child_method_ids = 'M_TRUST_NCG;M_TRUST_KRYLOV;M_TRUST_EXACT;M_GAUSS_NEWTON;M_LEVENBERG_MARQUARDT;M_TRUST_REGION_REFLECTIVE;M_DOGLEG'
WHERE method_id = 'MF_TRUST_REGION';

INSERT INTO method_hierarchy (
  hierarchy_id, parent_method_id, child_method_id, relation_type, depth,
  is_primary_parent, rationale, source_ids, confidence, last_verified
) VALUES
('MH_SMOOTH_LOCAL_SR1', 'MF_SMOOTH_LOCAL', 'M_SR1', 'is_a', 1, 'yes', 'SR1 is a quasi-Newton update classified with BFGS under Smooth local continuous optimization; its trust-region pairing is kept in related_method_ids.', 'S124;S056', 'medium', '2026-10-10'),
('MH_TRUST_REGION_DOGLEG', 'MF_TRUST_REGION', 'M_DOGLEG', 'is_a', 1, 'yes', 'Dogleg is classified under Trust-region methods.', 'S125;S056', 'medium', '2026-10-10'),
('MH_SMOOTH_LOCAL_CUBIC_REGULARIZATION', 'MF_SMOOTH_LOCAL', 'M_CUBIC_REGULARIZATION', 'is_a', 1, 'yes', 'Cubic regularization is a Newton-type method globalized by a regularization weight rather than a trust radius.', 'S126;S127', 'medium', '2026-10-10');

INSERT INTO terminology_aliases (
  term_id, target_type, target_id, label_ja, label_en, abbreviations_json,
  synonyms_json, domain_terms_json, misspellings_json, deprecated_terms_json,
  disambiguation_note, locale, rationale, source_ids_json, last_verified
) VALUES
('TERM_SR1', 'method', 'M_SR1', 'SR1法', 'Symmetric rank-one update', '["SR1"]',
 '["symmetric rank-1","SR1 update"]', '["Hessian近似更新"]', '[]', '[]',
 'BFGS(ランク2更新)とは別の手法。SR1はランク1更新で、近似が正定値とは限らない。', 'ja-JP,en',
 '略称と正式名をmethodへ解決する。', '["S124"]', '2026-10-10'),
('TERM_DOGLEG', 'method', 'M_DOGLEG', 'Dogleg法', 'Dogleg method', '[]',
 '["Powell dogleg","Powell hybrid method"]', '["折れ線step"]', '[]', '[]',
 'exact trust-regionやtrust-ncgとは別のtrust-region部分問題の解き方。', 'ja-JP,en',
 '名称をmethodへ解決する。', '["S125"]', '2026-10-10'),
('TERM_CUBIC_REGULARIZATION', 'method', 'M_CUBIC_REGULARIZATION', '三次正則化法', 'Cubic regularization', '["ARC"]',
 '["cubic regularisation","adaptive cubic regularisation","cubic regularization of Newton method"]', '["三次正則化Newton法"]', '[]', '[]',
 'trust-region法とは別の大域化。ARCは適応的な三次正則化(Adaptive Regularisation using Cubics)。', 'ja-JP,en',
 '略称・綴り(regularization/regularisation)をmethodへ解決する。', '["S126","S127"]', '2026-10-10');

INSERT INTO evidence_links (
  evidence_link_id, source_id, target_table, target_id, supported_field,
  claim_summary, evidence_role, confidence, last_verified
) VALUES
('EL004216', 'S124', 'methods', 'M_SR1', 'row', '対称ランク1更新でHessian近似を更新する準Newton法。', 'supporting_or_primary', 'medium', '2026-10-10'),
('EL004217', 'S056', 'methods', 'M_SR1', 'row', '対称ランク1更新でHessian近似を更新する準Newton法。', 'supporting_or_primary', 'medium', '2026-10-10'),
('EL004218', 'S002', 'methods', 'M_SR1', 'row', '対称ランク1更新でHessian近似を更新する準Newton法。', 'supporting_or_primary', 'medium', '2026-10-10'),
('EL004219', 'S125', 'methods', 'M_DOGLEG', 'row', 'Newtonとcauchy方向を折れ線でつなぐ信頼領域step。', 'supporting_or_primary', 'medium', '2026-10-10'),
('EL004220', 'S056', 'methods', 'M_DOGLEG', 'row', 'Newtonとcauchy方向を折れ線でつなぐ信頼領域step。', 'supporting_or_primary', 'medium', '2026-10-10'),
('EL004221', 'S002', 'methods', 'M_DOGLEG', 'row', 'Newtonとcauchy方向を折れ線でつなぐ信頼領域step。', 'supporting_or_primary', 'medium', '2026-10-10'),
('EL004222', 'S126', 'methods', 'M_CUBIC_REGULARIZATION', 'row', '三次正則化項付き二次モデルの最小化でNewton型更新を行う。', 'supporting_or_primary', 'medium', '2026-10-10'),
('EL004223', 'S127', 'methods', 'M_CUBIC_REGULARIZATION', 'row', '三次正則化項付き二次モデルの最小化でNewton型更新を行う。', 'supporting_or_primary', 'medium', '2026-10-10'),
('EL004224', 'S056', 'methods', 'M_CUBIC_REGULARIZATION', 'row', '三次正則化項付き二次モデルの最小化でNewton型更新を行う。', 'supporting_or_primary', 'medium', '2026-10-10');
