export const traceFrameFixture = {
  frame_index: 0,
  iteration: 0,
  oracle_evaluations: 0,
  elapsed_steps: 0,
  elapsed_time_ms: 0,
  event_type: "future-event",
  decision: "not_applicable",
  explanation_key: "trace.future-event",
  event_label_ja: null,
  event_label_en: null,
  keyframe: true,
  points: [],
  vectors: [],
  metrics: [],
  payload: { nested: [1, true, null] },
};

export const algorithmTraceFixture = {
  contract_version: "1.0.0",
  dataset_version: "0.2.0",
  data_version: "1.0.0",
  trace_id: "dummy-educational",
  method_id: "M_EDUCATIONAL",
  profile_id: "profile-educational",
  objective_id: "objective-quadratic",
  scenario_id: "scenario-dummy",
  generator_id: "optimization-compass.educational-dummy",
  generator_version: "1.0.0",
  implementation_mapping_status: "not_applicable",
  implementation_id: null,
  objective: { family: "quadratic" },
  preset: { preset_id: "dummy" },
  parameters: {},
  initial_state: { point: [2, -1] },
  seed: { status: "not_applicable", value: null },
  evaluation_budget: 20,
  stopping: { max_evaluations: 20 },
  environment: { runtime: "educational", version: "1.0.0" },
  fairness_statement: "同じ条件を使う。",
  frames: [traceFrameFixture],
  terminal_status: "converged",
  terminal_summary_ja: "完了",
  terminal_summary_en: "Complete",
  source_ids: ["S001"],
};
