export interface Observation { x: number; value: number; observed_value: number }
export interface PredictivePoint { x: number; true_value: number; mean: number; lower: number; upper: number; acquisition: number }
export interface SurrogateFrame {
  frame_index: number; oracle_evaluations: number; observations: Observation[];
  predictive_summary: PredictivePoint[]; selected_point: number | null;
  selected_mean: number | null; selected_uncertainty: number | null; selected_acquisition: number | null;
  incumbent_x: number; incumbent_value: number; random_incumbent_value: number; explanation_ja: string;
}
export interface SurrogateUncertaintyPayload {
  renderer_family: "surrogate_uncertainty"; renderer_contract_version: "1.0.0";
  artifact_kind: "executable_trace"; method_id: "M_BAYESIAN_OPT_GP";
  comparison_method_id: "M_RANDOM_SEARCH"; acquisition_id: "expected_improvement";
  strategy: "exploit" | "explore"; noise_preset: "noiseless" | "small_noise";
  seed: number; noise_std: number; exploration_xi: number; initial_design: number[];
  evaluation_budget: number; domain: number[]; objective_expression: string;
  truth_disclosure_ja: string; frames: SurrogateFrame[]; random_history: Observation[];
  fairness: { budget: number; initial_design: number[]; objective_id: string; domain: number[]; seed: number; comparison_method_id: "M_RANDOM_SEARCH" };
  limitations_ja: string[];
}
export interface VisualizationScenario {
  contract_version: "1.0.0"; dataset_version: string; data_version: "1.0.0";
  scenario_id: string; title_ja: string; title_en: string; purpose: "method_intuition" | "sensitivity" | "failure_mode";
  problem_definition_id: string; problem_instance_id: string; lesson_id: string; experiment_id: string;
  run_id: string; artifact_id: string; artifact_kind: "executable_trace"; source_ids: string[];
  last_verified: string; payload: SurrogateUncertaintyPayload;
}
export interface VisualizationScenarioIndexEntry { scenario_id: string; title_ja: string; strategy: "exploit" | "explore"; noise_preset: "noiseless" | "small_noise"; path: string; bytes: number; sha256: string }
export interface VisualizationScenarioIndex { contract_version: "1.0.0"; dataset_version: string; data_version: "1.0.0"; scenarios: VisualizationScenarioIndexEntry[] }

function object(value: unknown, field: string): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(`${field} must be an object.`); return value as Record<string, unknown>; }
function exact(data: Record<string, unknown>, expected: readonly string[], field: string): void { const allowed = new Set(expected); const unknown = Object.keys(data).filter((key) => !allowed.has(key)); const missing = expected.filter((key) => !Object.prototype.hasOwnProperty.call(data, key)); if (unknown.length) throw new Error(`${field} has unknown fields: ${unknown.join(", ")}.`); if (missing.length) throw new Error(`${field} is missing fields: ${missing.join(", ")}.`); }
function string(value: unknown, field: string): string { if (typeof value !== "string" || !value) throw new Error(`${field} must be a string.`); return value; }
function number(value: unknown, field: string): number { if (typeof value !== "number" || !Number.isFinite(value)) throw new Error(`${field} must be finite.`); return value; }
function array<T>(value: unknown, field: string, parse: (value: unknown, field: string) => T): T[] { if (!Array.isArray(value)) throw new Error(`${field} must be an array.`); return value.map((item, index) => parse(item, `${field}[${index}]`)); }
function nullableNumber(value: unknown, field: string): number | null { return value === null ? null : number(value, field); }
function literal<T extends string>(value: unknown, allowed: readonly T[], field: string): T { if (!allowed.includes(value as T)) throw new Error(`${field} is unsupported.`); return value as T; }

export function parseVisualizationScenarioIndex(value: unknown): VisualizationScenarioIndex {
  const data = object(value, "VisualizationScenarioIndex");
  exact(data, ["contract_version", "dataset_version", "data_version", "scenarios"], "VisualizationScenarioIndex");
  if (data.contract_version !== "1.0.0" || data.data_version !== "1.0.0") throw new Error("Unsupported VisualizationScenarioIndex version.");
  return { contract_version: "1.0.0", data_version: "1.0.0", dataset_version: string(data.dataset_version, "dataset_version"), scenarios: array(data.scenarios, "scenarios", (raw, field) => { const item = object(raw, field); const hash = string(item.sha256, `${field}.sha256`); if (!/^[0-9a-f]{64}$/u.test(hash)) throw new Error(`${field}.sha256 is invalid.`); return { scenario_id: string(item.scenario_id, `${field}.scenario_id`), title_ja: string(item.title_ja, `${field}.title_ja`), strategy: literal(item.strategy, ["exploit", "explore"] as const, `${field}.strategy`), noise_preset: literal(item.noise_preset, ["noiseless", "small_noise"] as const, `${field}.noise_preset`), path: string(item.path, `${field}.path`), bytes: number(item.bytes, `${field}.bytes`), sha256: hash }; }) };
}

export function parseVisualizationScenario(value: unknown): VisualizationScenario {
  const data = object(value, "VisualizationScenario"); const payload = object(data.payload, "payload");
  exact(data, ["contract_version", "dataset_version", "data_version", "scenario_id", "title_ja", "title_en", "purpose", "problem_definition_id", "problem_instance_id", "lesson_id", "experiment_id", "run_id", "artifact_id", "artifact_kind", "source_ids", "last_verified", "payload"], "VisualizationScenario");
  exact(payload, ["renderer_family", "renderer_contract_version", "artifact_kind", "method_id", "comparison_method_id", "acquisition_id", "strategy", "noise_preset", "seed", "noise_std", "exploration_xi", "initial_design", "evaluation_budget", "domain", "objective_expression", "truth_disclosure_ja", "frames", "random_history", "fairness", "limitations_ja"], "payload");
  if (data.contract_version !== "1.0.0" || data.data_version !== "1.0.0" || payload.renderer_contract_version !== "1.0.0" || payload.renderer_family !== "surrogate_uncertainty") throw new Error("Unsupported VisualizationScenario contract.");
  const parseObservation = (raw: unknown, field: string): Observation => { const item = object(raw, field); return { x: number(item.x, `${field}.x`), value: number(item.value, `${field}.value`), observed_value: number(item.observed_value, `${field}.observed_value`) }; };
  const frames = array(payload.frames, "payload.frames", (raw, field): SurrogateFrame => { const item = object(raw, field); return { frame_index: number(item.frame_index, `${field}.frame_index`), oracle_evaluations: number(item.oracle_evaluations, `${field}.oracle_evaluations`), observations: array(item.observations, `${field}.observations`, parseObservation), predictive_summary: array(item.predictive_summary, `${field}.predictive_summary`, (pointRaw, pointField) => { const point = object(pointRaw, pointField); return { x: number(point.x, `${pointField}.x`), true_value: number(point.true_value, `${pointField}.true_value`), mean: number(point.mean, `${pointField}.mean`), lower: number(point.lower, `${pointField}.lower`), upper: number(point.upper, `${pointField}.upper`), acquisition: number(point.acquisition, `${pointField}.acquisition`) }; }), selected_point: nullableNumber(item.selected_point, `${field}.selected_point`), selected_mean: nullableNumber(item.selected_mean, `${field}.selected_mean`), selected_uncertainty: nullableNumber(item.selected_uncertainty, `${field}.selected_uncertainty`), selected_acquisition: nullableNumber(item.selected_acquisition, `${field}.selected_acquisition`), incumbent_x: number(item.incumbent_x, `${field}.incumbent_x`), incumbent_value: number(item.incumbent_value, `${field}.incumbent_value`), random_incumbent_value: number(item.random_incumbent_value, `${field}.random_incumbent_value`), explanation_ja: string(item.explanation_ja, `${field}.explanation_ja`) }; });
  const fairnessRaw = object(payload.fairness, "payload.fairness");
  return { contract_version: "1.0.0", data_version: "1.0.0", dataset_version: string(data.dataset_version, "dataset_version"), scenario_id: string(data.scenario_id, "scenario_id"), title_ja: string(data.title_ja, "title_ja"), title_en: string(data.title_en, "title_en"), purpose: literal(data.purpose, ["method_intuition", "sensitivity", "failure_mode"] as const, "purpose"), problem_definition_id: string(data.problem_definition_id, "problem_definition_id"), problem_instance_id: string(data.problem_instance_id, "problem_instance_id"), lesson_id: string(data.lesson_id, "lesson_id"), experiment_id: string(data.experiment_id, "experiment_id"), run_id: string(data.run_id, "run_id"), artifact_id: string(data.artifact_id, "artifact_id"), artifact_kind: literal(data.artifact_kind, ["executable_trace"] as const, "artifact_kind"), source_ids: array(data.source_ids, "source_ids", string), last_verified: string(data.last_verified, "last_verified"), payload: { renderer_family: "surrogate_uncertainty", renderer_contract_version: "1.0.0", artifact_kind: literal(payload.artifact_kind, ["executable_trace"] as const, "payload.artifact_kind"), method_id: literal(payload.method_id, ["M_BAYESIAN_OPT_GP"] as const, "payload.method_id"), comparison_method_id: literal(payload.comparison_method_id, ["M_RANDOM_SEARCH"] as const, "payload.comparison_method_id"), acquisition_id: literal(payload.acquisition_id, ["expected_improvement"] as const, "payload.acquisition_id"), strategy: literal(payload.strategy, ["exploit", "explore"] as const, "payload.strategy"), noise_preset: literal(payload.noise_preset, ["noiseless", "small_noise"] as const, "payload.noise_preset"), seed: number(payload.seed, "payload.seed"), noise_std: number(payload.noise_std, "payload.noise_std"), exploration_xi: number(payload.exploration_xi, "payload.exploration_xi"), initial_design: array(payload.initial_design, "payload.initial_design", number), evaluation_budget: number(payload.evaluation_budget, "payload.evaluation_budget"), domain: array(payload.domain, "payload.domain", number), objective_expression: string(payload.objective_expression, "payload.objective_expression"), truth_disclosure_ja: string(payload.truth_disclosure_ja, "payload.truth_disclosure_ja"), frames, random_history: array(payload.random_history, "payload.random_history", parseObservation), fairness: { budget: number(fairnessRaw.budget, "fairness.budget"), initial_design: array(fairnessRaw.initial_design, "fairness.initial_design", number), objective_id: string(fairnessRaw.objective_id, "fairness.objective_id"), domain: array(fairnessRaw.domain, "fairness.domain", number), seed: number(fairnessRaw.seed, "fairness.seed"), comparison_method_id: literal(fairnessRaw.comparison_method_id, ["M_RANDOM_SEARCH"] as const, "fairness.comparison_method_id") }, limitations_ja: array(payload.limitations_ja, "payload.limitations_ja", string) } };
}
